// Centralised inline-style tokens for VoiceBox
const S = {
  app:      { minHeight:"100vh", background:"var(--bg)", color:"var(--text)", fontFamily:"system-ui,sans-serif", fontSize:14 },
  nav:      { display:"flex", alignItems:"center", justifyContent:"space-between", padding:"10px 22px", background:"var(--nav-bg)", borderBottom:"1px solid var(--border)", position:"sticky", top:0, zIndex:100 },
  logo:     { display:"flex", alignItems:"center", gap:8, cursor:"pointer" },
  logoMark: { width:30, height:30, borderRadius:8, background:"linear-gradient(135deg,var(--accent-strong),var(--accent))", display:"flex", alignItems:"center", justifyContent:"center", fontSize:15 },
  logoTxt:  { fontWeight:900, fontSize:15, color:"var(--text)" },
  page:     { maxWidth:1200, margin:"0 auto", padding:"26px 22px" },
  card:     { background:"var(--card-bg)", border:"1px solid var(--border)", borderRadius:14, padding:18 },
  g2:       { display:"grid", gridTemplateColumns:"1fr 1fr", gap:14 },
  g3:       { display:"grid", gridTemplateColumns:"1fr 1fr 1fr", gap:14 },
  g4:       { display:"grid", gridTemplateColumns:"repeat(4,1fr)", gap:12 },
  label:    { fontSize:10, fontWeight:700, color:"var(--text-muted)", textTransform:"uppercase", letterSpacing:".06em", marginBottom:4, display:"block" },
  input:    { width:"100%", background:"var(--muted-panel-bg)", border:"1px solid var(--border)", borderRadius:8, padding:"9px 12px", color:"var(--text)", fontSize:13, outline:"none", boxSizing:"border-box" },
  textarea: { width:"100%", background:"var(--muted-panel-bg)", border:"1px solid var(--border)", borderRadius:8, padding:"9px 12px", color:"var(--text)", fontSize:13, outline:"none", boxSizing:"border-box", resize:"vertical" },
  select:   { width:"100%", background:"var(--muted-panel-bg)", border:"1px solid var(--border)", borderRadius:8, padding:"9px 12px", color:"var(--text)", fontSize:13, outline:"none", boxSizing:"border-box" },
  btn:      { padding:"9px 18px", borderRadius:8, border:"none", cursor:"pointer", fontWeight:700, fontSize:13 },
  btnTeal:  { background:"linear-gradient(135deg,var(--accent-strong),var(--accent))", color:"var(--panel-text, white)" },
  btnAmber: { background:"linear-gradient(135deg,#B45309,#92400E)", color:"white" },
  btnBlue:  { background:"linear-gradient(135deg,#3B82F6,#1D4ED8)", color:"white" },
  btnGhost: { background:"var(--muted-panel-bg)", border:"1px solid var(--border)", color:"var(--text)" },
  btnDanger:{ background:"rgba(239,68,68,.14)", border:"1px solid rgba(239,68,68,.3)", color:"#fca5a5" },
  btnFull:  { width:"100%", padding:"11px", borderRadius:9, border:"none", cursor:"pointer", fontWeight:800, fontSize:13 },
  badge:    { padding:"2px 8px", borderRadius:100, fontSize:10, fontWeight:700 },
  badgeOpen:  { background:"rgba(245,158,11,.14)", border:"1px solid rgba(245,158,11,.25)", color:"#FCD34D" },
  badgeProg:  { background:"rgba(59,130,246,.14)", border:"1px solid rgba(59,130,246,.25)", color:"#93C5FD" },
  badgeRes:   { background:"rgba(16,185,129,.14)", border:"1px solid rgba(16,185,129,.25)", color:"#6EE7B7" },
  badgeAnon:  { background:"rgba(139,92,246,.14)", border:"1px solid rgba(139,92,246,.25)", color:"#C4B5FD" },
  statCard: { background:"var(--card-bg)", border:"1px solid var(--border)", borderRadius:12, padding:16 },
  statNum:  { fontSize:24, fontWeight:900, color:"var(--text)" },
  statLbl:  { fontSize:10, color:"var(--text-muted)", fontWeight:600, marginTop:3 },
  chip:     { padding:"5px 11px", borderRadius:8, fontSize:11, fontWeight:600, cursor:"pointer", border:"1px solid var(--border)", background:"var(--muted-panel-bg)", color:"var(--text)", display:"inline-block", margin:"3px 3px 3px 0" },
  chipSel:  { border:"1px solid var(--accent-border)", background:"var(--accent-bg)", color:"var(--accent)" },
  pillSchool:  { background:"rgba(245,158,11,.18)", border:"1px solid rgba(245,158,11,.4)",  color:"#FCD34D" },
  pillDept:    { background:"rgba(168,85,247,.18)", border:"1px solid rgba(168,85,247,.4)",  color:"#D8B4FE" },
  pillStaff:   { background:"rgba(59,130,246,.18)", border:"1px solid rgba(59,130,246,.4)",  color:"#93C5FD" },
  pillStudent: { background:"rgba(16,185,129,.18)", border:"1px solid rgba(16,185,129,.4)",  color:"#6EE7B7" },
  pill:        { padding:"2px 9px", borderRadius:100, fontSize:10, fontWeight:800, letterSpacing:".04em" },
};

export default S;
